#!/bin/sh

ver="0.4"
name="$1"
workdir=$(mktemp -d "/tmp/${name}.XXXXXXXXXX")
scf="${name}.scf"
lrp="${name}.lrp"
qth="${name}.qth"
scfdirname="${workdir}/${scf}"
lrpdirname="${workdir}/${lrp}"
qthdirname="${workdir}/${qth}"
lat="$2"
lon="$3"
theight="$4"
rheight="$5"
freq="$6"
erp="$7"
pol="$8"
db="$9"
hd="$10"
srtm="$11"
workname="${name}_${freq}_${theight}_${rheight}_${erp}"
workdirname="${workdir}/${workname}"
currdir=$(pwd)
SPLAT="splat"

usage()
{
	echo $(basename $0) version ${ver}
	echo
	echo Description:
	echo Helper script that generates kmz file
	echo
	echo $0 name lat lon theight rheight freq erp pol db hd sdf-dir
	echo
	echo "name\t- something describing"
	echo "lat\t- latitude in decimal form (e.g 57.694306)"
	echo "lon\t- longitude in decimal form (e.g -12.058889)"
	echo "theight\t- transmitter antenna height above ground (meters)"
	echo "rheight\t- receiver antenna height above ground (meters)"
	echo "freq\t- frequency (20-20000 MHz)"
	echo "erp\t- ERP (Watt)"
	echo "pol\t- polarization (0=horizontal, 1=vertical)"
	echo "db\t- lower threshold (dBuV/m)"
	echo "hd\t- use splat-hd (0=splat, 1=splat-hd)"
	echo "sdf-dir\t- absolute path to dir with sdf files"
}

gen_scf()
{
cat << EOF >> ${scfdirname}
; SPLAT! Signal Color Definition File
130: 255,   0, 255
115: 192,   0, 192
110: 160,   0, 160
105: 128,   0, 128
100:   0,   0, 255
 95:   0,   0, 224
 90:   0,   0, 192
 85:   0,   0, 128
 80:   0, 255, 255
 75:   0, 224, 224
 70:   0, 192, 192
 65:   0, 128, 128
 60:   0, 255,   0
 55:   0, 224,   0
 50:   0, 192,   0
 45:   0, 160,   0
 40:   0, 128,   0
 35: 255, 255,   0
 30: 192, 192,   0
 25: 160, 160,   0
 20: 128, 128,   0
 15: 255,   0,   0
 10: 192,   0,   0
  5: 160,   0,   0
  0: 128,   0,   0
EOF
}

gen_lrp()
{
cat << EOF >> ${lrpdirname}
15.000  ; Earth Dielectric Constant (Relative permittivity)
0.005   ; Earth Conductivity (Siemens per meter)
301.000 ; Atmospheric Bending Constant (N-units)
${freq} ; Frequency in MHz (20 MHz to 20 GHz)
6       ; Radio Climate (5 = Continental Temperate)
1       ; Polarization (0 = Horizontal, 1 = Vertical)
0.50    ; Fraction of situations (50% of locations)
0.90    ; Fraction of time (90% of the time)
${erp}  ; Effective Radiated Power (ERP) in Watts (optional)
EOF
}

gen_qth()
{
	echo ${name} > ${qthdirname}
	echo ${lat} >> ${qthdirname}
	echo ${lon} >> ${qthdirname}
	echo ${theight}m >> ${qthdirname}
}

run_splat()
{
	cd ${workdir}
	${SPLAT} -t ${qth} -L ${rheight} -kml -m 1.333 -olditm -sc -ngs -gc 8 -db ${db} -metric -d ${srtm} -o ${workname}
	cd ${currdir}
}

convert_ppm()
{
	convert -transparent "#ffffff" ${workdirname}.ppm ${workdirname}_tmp.png
	rm ${workdirname}.ppm
	convert -alpha on -channel a -evaluate subtract 25% ${workdirname}_tmp.png ${workdirname}.png
	rm ${workdirname}_tmp.png
}

modify_kml()
{
	sed -i "s|${workdir}||g" ${workdirname}.kml
	sed -i "s|<name>SPLAT! HD</name>|<name>${workname}</name>|" ${workdirname}.kml
	sed -i "s/${workname}\.ppm/${workname}\.png/" ${workdirname}.kml
}

pack_kmz()
{
	zip -j ${workname}.kmz ${workdirname}.kml ${workdirname}-ck.ppm ${workdirname}.png ${lrpdirname} ${qthdirname} ${scfdirname} ${workdir}/${name}-site_report.txt
}

remove_workdir()
{
	rm -rf -- ${workdir}
}

if [ $# -ne 11 ]; then
	usage
	remove_workdir
	exit 42
fi

if [ "${hd}" -eq 1 ]; then
	SPLAT="splat-hd"
fi

gen_scf
gen_lrp
gen_qth
run_splat
convert_ppm
modify_kml
pack_kmz
remove_workdir

exit 0
